### ISSUE TITLE
Don't use /var/tmp

### ISSUE THREAD

**Issue by mrueg** [gentoo/porticron#2]
/var/tmp can be a tmpfs on some systems, which results in getting the porticron files lost. It would be better to use /var/cache as default.

**Comment by hartwork** [comment]
If the mail last sent is not store somewhere, a hash of it is not cached data in my eyes, since it cannot be re-generated. I would rather propose use of `/var/lib/`, then.

On a side note, FHS's definition of `/var/tmp` is

> Temporary files preserved between system reboots

see http://www.pathname.com/fhs/pub/fhs-2.3.html#VARTMPTEMPORARYFILESPRESERVEDBETWEE .
So to have all of `/var/tmp` in tmpfs rather than just say `/var/tmp/portage` would be a system misconfiguration in my eyes, for the record.

Best, Sebastian

**Comment by mrueg** [comment]
Sorry, you're right. I guess i mixed it up with tmpfs on /var/tmp/portage.
